---
abstract: 'Fast, compact, powerful binary (de-)serialization'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Sereal::Decoder: 2.01
  Sereal::Encoder: 2.01
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sereal
no_index:
  directory:
    - t
    - inc
requires:
  Sereal::Decoder: 2.01
  Sereal::Encoder: 2.01
  perl: 5.008
resources:
  bugtracker: https://github.com/Sereal/Sereal/issues
  repository: git://github.com/Sereal/Sereal.git
version: 2.011
